name: Prettier Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i -g yarn 

      - name: Install dependencies
        run:  yarn
        
      - name: Check code formatting
        run: yarn format:test